[workspace]
authors = ["tomastmk <tomasamadio@gmail.com>"]
channels = ["conda-forge","bioconda"]
name = "New"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.15,<3.14"
r-base = ">=4.3,<4.4"
yazi = ">=26.5.6,<27"
biopython = ">=1.88,<2"
pyrodigal = ">=3.7.1,<4"
diamond = ">=2.2.2,<3"
polars = ">=1.42.1,<2"
xdg = ">=6.0.0,<7"
igraph = ">=1.0.1,<2"
leidenalg = ">=0.12.0,<0.13"
tqdm = ">=4.68.4,<5"
macsyfinder = ">=2.1.6,<3"
csvlens = ">=0.15.1,<0.16"
seqkit = ">=2.13.0,<3"
emboss = ">=6.6.0,<7"
jalview = ">=2.11.5.1,<3"
mafft = ">=7.526,<8"
alv = ">=1.8.3,<2"
aliview = ">=1.32,<2"
datasets = ">=5.0.1,<6"
ncbi-datasets-cli = ">=18.37.0,<19"
entrez-direct = ">=26.0,<27"
git = ">=2.55.0,<3"
eza = ">=0.23.5,<0.24"
compilers = ">=1.11.0,<2"
c-compiler = ">=1.11.0,<2"
cxx-compiler = ">=1.11.0,<2"
radian = ">=0.6.15,<0.7"
r-httpgd = ">=2.0.4,<3"
r-ggplot2 = ">=3.5.2,<4"
"r-data.table" = ">=1.17.8,<2"
r-dplyr = ">=1.1.4,<2"
r-biocmanager = ">=1.30.26,<2"
bioconductor-biostrings = ">=2.70.1,<3"
jupyterlab = ">=4.6.3,<5"
pixi-kernel = ">=0.7.1,<0.8"
rust = ">=1.98.0,<1.99"
maxalign-rs = ">=0.3.1,<0.4"
trimal = ">=1.5.1,<2"
pal2nal = ">=14.1,<15"
unibilium = ">=2.1.4,<3"
nvim = ">=0.12.5,<0.13"
iqtree = ">=3.1.3,<4"
matplotlib = ">=3.11.1,<4"
fasttree = ">=2.2.0,<3"
hyphy = ">=2.5.101,<3"
newick_utils = ">=1.6,<2"
